### ISSUE TITLE
Feature request - allow other containers to control the manager interface

### ISSUE THREAD

**Issue by martinfrances107** [nippe/alpine-varnish-docker#1]
Hello Niklas,

I like this project very much, would you consider accepting this feature request? I am about to include a pull request

I am building a cluster of containers for a Drupal8 project with a varnish reverse proxy cache.

The Drupal8 container needs to reach into the varnish container and invalidate cache entries based on how the users change the data - it does this through the management interface.

The changes in the pull request adds a -T to  the varnishd command line options  

for example 

varnishd -f /etc/varnish/default.vcl -s malloc,100M -a 0.0.0.0:80 -T localhost:6082 -F -p cli_timeout=60 -p connect_timeout=60

so by default localhost:6082 is used but this option is under the control of two new environment variables which could for example be

 environment:
      VARNISH_ADMIN_IP: php_service
      VARNISH_ADMIN_PORT: 1234

Anyway I hope you think this is useful.

**Comment by nippe** [comment]
Hi Martin,

Sounds really good! 

I'll go ahead and approve it!
