### ISSUE TITLE
No longer builds correctly.

### ISSUE THREAD

**Issue by martinfrances107** [nippe/alpine-varnish-docker#3]
When I try 

docker build . 

From a fresh build ... something in configure -> make -> make install breaks

the first warning I see is 

./configure: ./configure.lineno: line 1: /usr/bin/file: not found

so its looks like something in the environment alpine:edge build has changed.

Problems like this occur when using the edge/beta versions. There is no drama here - just life :)

I am just posting early before looking at this in more detail... 

In case there is a reproducibility issue I am on the mac beta which is rapidly evolving  also. currently running  1.12.0-rc4-beta20 -- just saying.

**Comment by nippe** [comment]
Ah, ok. 

Off vacationing at the moment. WIll look into when I get back.

Thanks!

**Comment by nippe** [comment]
So, changed the base image from edge to latest of alpine. Seems to work.
